name: 02-ci-cd-composite-actions
run-name: ${{ github.workflow}} - ${{ github.sha }}
on: [workflow_dispatch]
jobs: 
  build:
    runs-on: ubuntu-latest
    outputs:
      artefact-name: ${{ steps.build.outputs.ARTEFACT_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: ls
        run: ls -la
      - name: Build Artefact
        id: build
        run: |
          ARTEFACT_NAME=sample-app-$(date +%Y%m%d%H%M%S)-$(git rev-parse --short HEAD)
          echo "ARTEFACT_NAME=$ARTEFACT_NAME" >> $GITHUB_ENV
          echo "ARTEFACT_NAME=$ARTEFACT_NAME" >> $GITHUB_OUTPUT
      - name: check env var
        run: echo $ARTEFACT_NAME


  plan-dev:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform_plan
        with:
          ENV: Dev
          ARTEFACT_NAME: ${{ needs.build.outputs.artefact-name }}

  deploy-dev:
    needs: [plan-dev, build]
    runs-on: ubuntu-latest
    environment: 
      name: Dev
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform_deploy
        with:
          ENV: Dev
          ARTEFACT_NAME: ${{ needs.build.outputs.artefact-name }}

  plan-uat:
    needs: [deploy-dev, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform_plan
        with:
          ENV: UAT
          ARTEFACT_NAME: ${{ needs.build.outputs.artefact-name }}

  deploy-uat:
    needs: [plan-uat, build]
    runs-on: ubuntu-latest
    environment: 
      name: UAT
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform_deploy
        with:
          ENV: UAT
          ARTEFACT_NAME: ${{ needs.build.outputs.artefact-name }}