name: 04-cd
run-name: ${{ github.workflow}} - ${{ github.sha }}
on:
  # push:
  workflow_dispatch:
    inputs:
      REGIONS:
        description: 'Prod Regions'
        required: false
        default: '["au", "us", "ca"]'
      ARTEFACT_NAME:
        description: 'Artefact Name'
        required: true
        type: string

  workflow_call:
    inputs:
      REGIONS:
        description: 'Prod Regions'
        required: false
        default: '["au", "us", "ca"]'
      ARTEFACT_NAME:
        description: 'Artefact Name'
        required: true
        type: string

jobs:
  deploy-dev:
    name: Deploy to Dev
    needs: [build]
    uses: whathelll/sample-app/.github/workflows/03-reusable-terraform-plan-deploy.yml@main
    with:
      ENV: Dev
      ARTEFACT_NAME: ${{ needs.build.outputs.artefact-name }}
      # REGIONS: '["au"]'
      REGIONS: '["au"]'
    secrets: inherit

  deploy-uat:
    name: Deploy to UAT
    needs: [build, deploy-dev]
    uses: whathelll/sample-app/.github/workflows/03-reusable-terraform-plan-deploy.yml@main
    with:
      ENV: UAT
      ARTEFACT_NAME: ${{ needs.build.outputs.artefact-name }}
      # REGIONS: '["au", "us"]'
      REGIONS: ${{ github.event_name == 'workflow_dispatch' && inputs.REGIONS || '["au", "us"]' }} 
    secrets: inherit