name: 04-ci
run-name: ${{ github.workflow}} - ${{ github.sha }}
on: 
  # push:
  workflow_dispatch:
    inputs:
      REGIONS:
        description: 'Regions'
        required: true
        default: '["au", "us", "ca"]'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artefact-name: ${{ steps.build.outputs.ARTEFACT_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: ls
        run: ls -la
      - name: Build Artefact
        id: build
        run: |
          ARTEFACT_NAME=sample-app-$(date +%Y%m%d%H%M%S)-$(git rev-parse --short HEAD)
          echo "ARTEFACT_NAME=$ARTEFACT_NAME" >> $GITHUB_ENV
          echo "ARTEFACT_NAME=$ARTEFACT_NAME" >> $GITHUB_OUTPUT
      - name: check env var
        run: echo $ARTEFACT_NAME

  deploy-dev:
    name: Deploy to Dev
    needs: [build]
    uses: whathelll/sample-app/.github/workflows/03-reusable-terraform-plan-deploy.yml@main
    with:
      ENV: Dev
      ARTEFACT_NAME: ${{ needs.build.outputs.artefact-name }}
      # REGIONS: '["au"]'
      REGIONS: ${{ github.event_name == 'workflow_dispatch' && github.inputs.REGIONS || '["au"]' }} 
    secrets: inherit

  deploy-uat:
    name: Deploy to UAT
    needs: [build, deploy-dev]
    uses: whathelll/sample-app/.github/workflows/03-reusable-terraform-plan-deploy.yml@main
    with:
      ENV: UAT
      ARTEFACT_NAME: ${{ needs.build.outputs.artefact-name }}
      # REGIONS: '["au", "us"]'
      REGIONS: ${{ github.event_name == 'workflow_dispatch' && github.inputs.REGIONS || '["au", "us"]' }} 
    secrets: inherit