name: 04-cd
run-name: ${{ github.workflow}} - ${{ github.sha }}
on:
  # push:
  workflow_dispatch:
    inputs:
      REGIONS:
        description: 'Prod Regions'
        required: false
        type: string
        default: '["au", "us", "ca"]'
      ARTEFACT_NAME:
        description: 'Artefact Name'
        required: true
        type: string

  workflow_call:
    inputs:
      REGIONS:
        description: 'Prod Regions'
        required: false
        type: string
        default: '["au", "us", "ca"]'
      ARTEFACT_NAME:
        description: 'Artefact Name'
        required: true
        type: string

jobs:
  start-point:
    runs-on: ubuntu-latest
    steps:
      - name: Do Nothing
        run: echo "Doing Nothing"

  deploy-dev:
    name: Deploy Dev
    needs: [start-point]
    uses: whathelll/sample-app/.github/workflows/03-reusable-terraform-plan-deploy.yml@main
    with:
      ENV: Dev
      ARTEFACT_NAME: ${{ inputs.ARTEFACT_NAME }}
      # REGIONS: '["au"]'
      REGIONS: '["au"]'
    secrets: inherit

  deploy-uat:
    name: Deploy UAT
    needs: [deploy-dev]
    uses: whathelll/sample-app/.github/workflows/03-reusable-terraform-plan-deploy.yml@main
    with:
      ENV: UAT
      ARTEFACT_NAME: ${{ inputs.ARTEFACT_NAME }}
      # REGIONS: '["au", "us"]'
      REGIONS: ${{ github.event_name == 'workflow_dispatch' && inputs.REGIONS || '["au", "us"]' }} 
    secrets: inherit