name: ci-build
run-name: ${{ github.workflow}} - ${{ github.sha }}
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ls
        run: ls -la
      - name: Build Artefact
        id: build
        run: |
          echo "ARTEFACT_NAME=sample-app-$(date +%Y%m%d%H%M%S)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "ARTEFACT_NAME=sample-app-$(date +%Y%m%d%H%M%S)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: check env var
        run: echo $ARTEFACT_NAME


  deploy-dev:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      ARTEFACT_NAME: ${{ steps.build.outputs.artefact-name }}
    environment: 
      name: Dev
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Dev
        run: |  
          echo "Deploying $ARTEFACT_NAME to Dev"