name: ci-build
run-name: ${{ github.workflow}} - ${{ github.sha }}
on: [push]
jobs: 
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ls
        run: ls -la
      - name: Build Artefact
        run: echo "ARTEFACT_NAME=sample-app-$(date +%Y%m%d%H%M%S)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: check env var
        run: echo $ARTEFACT_NAME
        