on:
  workflow_call:
    inputs:
      ENV:  # environment
        description: 'environment'
        required: true
        type: string
        default: 'Dev'
      ARTEFACT_NAME:  # ARTEFACT_NAME
        description: 'ARTEFACT_NAME'
        required: true
        type: string
        default: ''

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: python print inherited secret
        env:
          MY_VAL: ${{ secrets.TEST_SECRET }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python
      - name: Terraform Planning for ${{ inputs.ENV }}
        shell: bash
        run: |  
          echo "Git Hash is $(git rev-parse --short HEAD)"
          PLAN="this is the plan for deploying $ARTEFACT_NAME to ${{ inputs.ENV }} with RunID: ${{github.run_id}}_${{ github.run_attempt }}"
          echo $PLAN
          echo $PLAN >> ${{github.run_id}}_${{ github.run_attempt }}_${{ inputs.ENV }}.plan
      - name: Upload plan for ${{ inputs.ENV }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.run_id}}_${{ github.run_attempt }}_${{ inputs.ENV }}.plan
          path: ${{github.run_id}}_${{ github.run_attempt }}_${{ inputs.ENV }}.plan
          retention-days: 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: plan
    steps:
      # - uses: actions/checkout@v4
      - name: Download plan for ${{ inputs.ENV }}
        uses: actions/download-artifact@v4
        with:
          name: ${{github.run_id}}_${{ github.run_attempt }}_${{ inputs.ENV }}.plan
      - name: Deploy to ${{ inputs.ENV }}
        run: |
          echo "Deploying $ARTEFACT_NAME to $ENV"
          cat ${{github.run_id}}_${{ github.run_attempt }}_${{ inputs.ENV }}.plan