on:
  workflow_call:
    inputs:
      ENV:  # environment
        description: 'environment'
        required: true
        type: string
        default: 'Dev'
      ARTEFACT_NAME:  # ARTEFACT_NAME
        description: 'ARTEFACT_NAME'
        required: true
        type: string
        default: ''
      REGIONS: 
        description: 'Regions'
        required: false
        type: string
        default: '["au"]'

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ${{ fromJson(inputs.REGIONS) }}
    steps:
      - uses: actions/checkout@v4
      - name: python print inherited secret
        env:
          MY_VAL: ${{ secrets.TEST_SECRET }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python
      - name: Terraform Planning for ${{ inputs.ENV }}
        shell: bash
        run: |  
          echo "Git Hash is $(git rev-parse --short HEAD)"
          PLAN="this is the plan for deploying $ARTEFACT_NAME to ${{ inputs.ENV }} with RunID: ${{ matrix.region }}_${{github.run_id}}_${{ github.run_attempt }}"
          echo $PLAN
          echo $PLAN >> ${{ matrix.region }}_${{github.run_id}}_${{ github.run_attempt }}_${{ inputs.ENV }}.plan
          # if matrix.region == 'us' exit 1
          if [ "${{ matrix.region }}" == "us" ]; then
            echo "Exiting with error"
            exit 1
          fi

      - name: Upload plan for ${{ inputs.ENV }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.region }}_${{github.run_id}}_${{ github.run_attempt }}_${{ inputs.ENV }}.plan
          path: ${{ matrix.region }}_${{github.run_id}}_${{ github.run_attempt }}_${{ inputs.ENV }}.plan
          retention-days: 1

  apply:
    name: Apply
    runs-on: ubuntu-latest
    needs: [plan]
    strategy:
      matrix:
        region: ${{ fromJson(inputs.REGIONS) }}
    environment: 
      name: ${{ inputs.ENV }}
    steps:
      # - uses: actions/checkout@v4
      - name: Download plan for ${{ inputs.ENV }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.region }}_${{github.run_id}}_${{ github.run_attempt }}_${{ inputs.ENV }}.plan
      - name: Deploy to ${{ inputs.ENV }}
        run: |
          echo "Deploying $ARTEFACT_NAME to $ENV"
          cat ${{ matrix.region }}_${{github.run_id}}_${{ github.run_attempt }}_${{ inputs.ENV }}.plan